services:
  db:
    image: postgres:16-alpine
    container_name: nbl_db
    environment:
      - POSTGRES_DB=NBL
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"

  api:
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    container_name: nbl_api
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=NBL;Username=postgres;Password=postgres
    depends_on:
      - db