services:
  db:
    image: postgres:16-alpine
    container_name: nbl_db
    environment:
      - POSTGRES_DB=NBL
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    container_name: nbl_api
    ports:
      - "2115:8080"
    environment:
      - ConnectionStrings__PostgresConnection=Host=db;Port=5432;Database=NBL;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
volumes:
  postgres_data:
  